### ISSUE TITLE
Module not found: Error: Part "part:@sanity/base/reset-icon" not implemented by any plugins

### ISSUE THREAD

**Issue by lexcorp** [sanity-io/squizzy#14]
When try run development I recieve: 

C:\squizzy\studio>npm run dev

> squizzy@1.0.0 dev C:\squizzy\studio
> sanity start

√ Checking configuration files...
| Compiling...webpack built a29f16388662b612a47a in 13436ms
√ Compiling...
Failed to compile.

Error in ./node_modules/@sanity/desk-tool/lib/actions/DiscardChangesAction.js
Module not found: Error: Part "part:@sanity/base/reset-icon" not implemented by any plugins
 @ ./node_modules/@sanity/desk-tool/lib/actions/DiscardChangesAction.js 12:40-79
 @ ./node_modules/@sanity/desk-tool/lib/defaultDocumentActions.js
 @ ./node_modules/@sanity/desk-tool/lib/defaultResolveDocumentActions.js (part:@sanity/base/document-actions/resolver)
 @ ./node_modules/@sanity/desk-tool/lib/components/DocumentActionShortcuts.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/DocumentPane.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/DocumentPaneProvider.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/Pane.js
 @ ./node_modules/@sanity/desk-tool/lib/DeskToolPanes.js
 @ ./node_modules/@sanity/desk-tool/lib/DeskTool.js
 @ ./node_modules/@sanity/desk-tool/lib/tool.js
 @ ./node_modules/@sanity/vision/lib/VisionTool.js (all:part:@sanity/base/tool)
 @ ./node_modules/@sanity/default-layout/lib/defaultLayoutRouter.js
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayoutContainer.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js

**Comment by amandakievet** [comment]
How did you resolve this? I'm seeing a similar issue now.
```
Failed to compile.

Error in ./node_modules/sanity-plugin-tabs/lib/index.js
Module not found: Error: Part "part:@sanity/base/warning-outline-icon" not implemented by any plugins
 @ ./node_modules/sanity-plugin-tabs/lib/index.js 22:49-98
 @ ./schemas/tabs/variantContent.ts
 @ ./schemas/schemas.ts (part:@sanity/base/schema)
 @ ./node_modules/@sanity/default-layout/lib/schemaErrors/SchemaErrorReporter.js
 @ ./node_modules/@sanity/default-layout/lib/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js
```

**Comment by niku-19** [comment]
@ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)

**Comment by orliyahTheCoder** [comment]
has nobody found the solution???? I am also trying to solve this😭
